# Generated by Django 2.0.13 on 2020-01-16 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_dialog_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialog',
            name='look',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dialog_log',
            name='look',
            field=models.IntegerField(default=0),
        ),
    ]
